"""TRI-CROWN annex utilities."""

from .math_process import (
    apply_caesar_shift,
    bigram_probabilities,
    causal_convolution,
    compose_process_and_wave,
    features_digest,
    fixed_point_key_binding,
    fourier_energy_ratios,
    green_convolution,
    huber_irls,
    interrogative_score,
    math_salt,
    matrix_exponential,
    modal_coordinates,
    riccati_gain,
    reverse_letters,
)
from .process import (
    caesar_cipher,
    diagonalize,
    digram_counts,
    discrete_process_noise,
    finite_horizon_lqr,
    mean_squared_deviation,
    process_matrix,
    rk4_convolution,
    van_loan_discretization,
    huber_irls as process_huber_irls,
)
from .kalman import (
    discretize_falling_body,
    process_noise_white_acc,
    kalman_predict,
    kalman_step,
    kalman_update,
)

__all__ = [
    "apply_caesar_shift",
    "bigram_probabilities",
    "causal_convolution",
    "compose_process_and_wave",
    "features_digest",
    "fixed_point_key_binding",
    "fourier_energy_ratios",
    "green_convolution",
    "huber_irls",
    "interrogative_score",
    "math_salt",
    "matrix_exponential",
    "modal_coordinates",
    "riccati_gain",
    "reverse_letters",
    "caesar_cipher",
    "diagonalize",
    "digram_counts",
    "discrete_process_noise",
    "finite_horizon_lqr",
    "mean_squared_deviation",
    "process_matrix",
    "rk4_convolution",
    "van_loan_discretization",
    "process_huber_irls",
    "discretize_falling_body",
    "process_noise_white_acc",
    "kalman_predict",
    "kalman_step",
    "kalman_update",
]
